version: '3.4'

services:
  chatible:
    image: chatible
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      -source:/usr/src/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: <DB_USERNAME_HERE>
      MONGO_INITDB_ROOT_PASSWORD: <DB_PASSWORD_HERE>
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <DB_USERNAME_HERE>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <DB_PASSWORD_HERE>
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --requirepass <REDIS_PASS_HERE> --loglevel warning

volumes:
  mongoDatabase:
  redis:
  source: